#
# See default configuration here: https://github.com/codecov/support/blob/master/codecov.yml
#
# For more options see: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a
#
# Codecov documentation is available here: https://codecov.io/docs

coverage:
  ignore:
  - generated/*
  - test/*
  - testutil-api/src/main/java/javaclasses/mealorder/testdata/*

  status:
    patch: false
    project:
      default:
        target: 95%


comment:
  layout: "header, diff, changes, uncovered"
